<?php
declare(strict_types=1);
ini_set('display_errors','0'); error_reporting(E_ALL);
if(session_status()===PHP_SESSION_NONE) session_start();
date_default_timezone_set('Africa/Lusaka');
require_once '../includes/conn.php'; require_once '../includes/auth.php';
$pharmacy_id=(int)($_SESSION['pharmacy_id']??0); $branch_id=(int)($_SESSION['branch_id']??0);
if($pharmacy_id<=0||$branch_id<=0){header('Location: ../login.php?error=session_expired');exit;}
$pharmacy_name='EchoTech POS'; $branch_name='Main Branch';
$s=$conn->prepare('SELECT name FROM pharmacies WHERE id=? LIMIT 1'); if($s){$s->bind_param('i',$pharmacy_id);$s->execute();$r=$s->get_result();if($x=$r->fetch_assoc()&&!empty($x['name']))$pharmacy_name=$x['name'];$s->close();}
$s=$conn->prepare('SELECT branch_name FROM branches WHERE id=? LIMIT 1'); if($s){$s->bind_param('i',$branch_id);$s->execute();$r=$s->get_result();if($x=$r->fetch_assoc()&&!empty($x['branch_name']))$branch_name=$x['branch_name'];$s->close();}
$categories=['General','Utilities','Staff Welfare','Logistics','Stock/Supplies','Other'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Expenses - <?=htmlspecialchars($pharmacy_name)?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="dist/css/style.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet"><style>
:root{--p:#0d6efd;--d:#dc3545;--w:#ffc107;--b:#e2e8f0;--bg:#f4f6f9}body{background:var(--bg);color:#1e293b}.page-wrapper{padding:1.25rem}.ec{background:#fff;border:1px solid var(--b);border-radius:14px;box-shadow:0 2px 8px rgba(15,23,42,.05)}.ic{width:44px;height:44px;border-radius:12px;display:inline-flex;align-items:center;justify-content:center;background:#eaf2ff;color:var(--p)}.sum{border:0;border-radius:14px;box-shadow:0 2px 8px rgba(15,23,42,.05)}.form-control,.form-select{min-height:44px;border-color:var(--b)}.expense-table thead th{background:#f8fafc;color:#334155;font-size:.78rem;text-transform:uppercase;letter-spacing:.4px;border-bottom:2px solid var(--b)}.expense-table td{padding:13px;border-color:#f1f5f9;vertical-align:middle}.amt{font-weight:800;color:var(--d);white-space:nowrap}.cat{background:#f1f5f9;color:#334155;border:1px solid var(--b)}.empty{padding:50px;color:#64748b}.filter{background:#f8fafc;border:1px solid var(--b);border-radius:12px}@media(max-width:768px){.page-wrapper{padding:.75rem}.expense-table{min-width:720px}}@media print{.no-print,#header,#aside,nav,footer{display:none!important}.page-wrapper{padding:0!important}body{background:#fff!important}.ec{box-shadow:none!important}}
</style></head><body><div id="main-wrapper"><?php if(file_exists('../includes/header.php'))require '../includes/header.php'; if(file_exists('../includes/aside.php'))require '../includes/aside.php'; ?><div class="page-wrapper"><div class="container-fluid">
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div class="d-flex align-items-center gap-3"><div class="ic"><i class="fas fa-receipt"></i></div><div><h3 class="fw-bold mb-1">Expenses</h3><div class="small text-muted"><?=htmlspecialchars($pharmacy_name)?> <span class="mx-1">•</span> <?=htmlspecialchars($branch_name)?></div></div></div><button class="btn btn-outline-dark fw-bold no-print" onclick="window.print()"><i class="fas fa-print me-1"></i>Print</button></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card sum h-100"><div class="card-body d-flex justify-content-between align-items-center"><div><div class="small text-muted fw-bold text-uppercase">Total Expenses</div><div id="total_display" class="fs-3 fw-bold text-danger">K0.00</div></div><i class="fas fa-money-bill-wave fa-lg text-danger"></i></div></div></div><div class="col-md-4"><div class="card sum h-100"><div class="card-body d-flex justify-content-between align-items-center"><div><div class="small text-muted fw-bold text-uppercase">This Month</div><div id="month_display" class="fs-3 fw-bold text-warning">K0.00</div></div><i class="fas fa-calendar-alt fa-lg text-warning"></i></div></div></div><div class="col-md-4"><div class="card sum h-100"><div class="card-body d-flex justify-content-between align-items-center"><div><div class="small text-muted fw-bold text-uppercase">Records</div><div id="count_display" class="fs-3 fw-bold text-primary">0</div></div><i class="fas fa-list-ol fa-lg text-primary"></i></div></div></div></div>
<div class="row g-4"><div class="col-lg-4"><div class="card ec"><div class="card-header bg-white p-3"><h5 class="fw-bold mb-1"><i class="fas fa-plus-circle text-primary me-2"></i>Record Expense</h5><small class="text-muted">Record a business expense for this branch.</small></div><div class="card-body p-3 p-lg-4"><form id="expenseForm" autocomplete="off"><div class="mb-3"><label class="form-label fw-semibold">Description</label><input name="name" id="expenseName" class="form-control" maxlength="150" placeholder="e.g. Electricity bill" required></div><div class="mb-3"><label class="form-label fw-semibold">Amount (K)</label><div class="input-group"><span class="input-group-text fw-bold">K</span><input type="number" name="amount" id="expenseAmount" class="form-control" min=".01" step=".01" required></div></div><div class="mb-3"><label class="form-label fw-semibold">Category</label><select name="category" id="expenseCategory" class="form-select"><?php foreach($categories as $c):?><option value="<?=htmlspecialchars($c)?>"><?=htmlspecialchars($c)?></option><?php endforeach;?></select></div><div class="mb-3"><label class="form-label fw-semibold">Expense Date</label><input type="date" name="date" id="expenseDate" class="form-control" value="<?=date('Y-m-d')?>" required></div><button id="submitBtn" class="btn btn-primary w-100 fw-bold py-2"><i class="fas fa-save me-1"></i>SAVE EXPENSE</button></form></div></div></div>
<div class="col-lg-8"><div class="card ec"><div class="card-header bg-white p-3"><div class="d-flex flex-column flex-md-row justify-content-between gap-3"><div><h5 class="fw-bold mb-1"><i class="fas fa-history text-primary me-2"></i>Expense History</h5><small class="text-muted">Branch expense records</small></div><div class="dropdown no-print"><button class="btn btn-sm btn-outline-danger dropdown-toggle fw-bold" data-bs-toggle="dropdown">CLEAR RECORDS</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item clear-btn" href="#" data-type="month">Clear This Month</a></li><li><a class="dropdown-item clear-btn text-danger" href="#" data-type="year">Clear This Year</a></li></ul></div></div></div><div class="card-body p-3"><div class="filter p-3 mb-3 no-print"><div class="row g-2"><div class="col-md-5"><label class="small fw-semibold">Search</label><input id="expenseSearch" class="form-control" placeholder="Description..."></div><div class="col-md-3"><label class="small fw-semibold">Category</label><select id="filterCategory" class="form-select"><option value="">All Categories</option><?php foreach($categories as $c):?><option value="<?=htmlspecialchars($c)?>"><?=htmlspecialchars($c)?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="small fw-semibold">From</label><input type="date" id="filterStart" class="form-control"></div><div class="col-md-2"><label class="small fw-semibold">To</label><input type="date" id="filterEnd" class="form-control"></div></div></div><div class="table-responsive"><table class="table table-hover expense-table mb-0"><thead><tr><th>Description</th><th>Category</th><th>Date</th><th class="text-end">Amount</th><th class="text-center no-print">Action</th></tr></thead><tbody id="expenses_list"><tr><td colspan="5" class="text-center py-4">Loading...</td></tr></tbody></table></div></div></div></div></div></div></div></div>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script>
(()=>{'use strict';let all=[];const localDate=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),x=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${x}`},today=()=>localDate(new Date()),esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;'),money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function load(){ $.getJSON('actions/expenses.php',{action:'list'}).done(r=>{if(r.status!=='success'){alert(r.message||'Unable to load expenses');return}all=r.expenses||[];render();$('#month_display').text('K'+money(r.month_total));}).fail(()=>$('#expenses_list').html('<tr><td colspan="5" class="text-center text-danger py-4">Unable to load expenses.</td></tr>'));}
function filtered(){const q=($('#expenseSearch').val()||'').trim().toLowerCase(),c=$('#filterCategory').val(),a=$('#filterStart').val(),b=$('#filterEnd').val();return all.filter(e=>(!q||String(e.name||'').toLowerCase().includes(q))&&(!c||e.category===c)&&(!a||e.expense_date>=a)&&(!b||e.expense_date<=b));}
function render(){const rows=filtered();let total=0;let html='';rows.forEach(e=>{const n=Number(e.amount||0);total+=n;html+=`<tr><td class="fw-bold">${esc(e.name)}</td><td><span class="badge cat">${esc(e.category||'General')}</span></td><td class="text-muted">${esc(e.expense_date)}</td><td class="text-end amt">K${money(n)}</td><td class="text-center no-print"><button class="btn btn-sm btn-outline-danger delete-expense" data-id="${Number(e.id)}" title="Delete"><i class="fas fa-trash-alt"></i></button></td></tr>`});if(!html)html='<tr><td colspan="5" class="text-center empty">No expenses found.</td></tr>';$('#expenses_list').html(html);$('#total_display').text('K'+money(total));$('#count_display').text(rows.length);}
$('#expenseForm').on('submit',function(e){e.preventDefault();const b=$('#submitBtn'),name=$('[name=name]').val().trim(),amount=Number($('[name=amount]').val()),date=$('[name=date]').val();if(!name||!Number.isFinite(amount)||amount<=0||!date){alert('Please enter a valid description, amount and date.');return}b.prop('disabled',true).text('SAVING...');$.post('actions/expenses.php',$(this).serialize()+'&action=add',null,'json').done(r=>{if(r.status==='success'){this.reset();$('#expenseDate').val(today());load()}else alert(r.message||'Unable to save expense')}).fail(()=>alert('Server error while saving expense.')).always(()=>b.prop('disabled',false).html('<i class="fas fa-save me-1"></i>SAVE EXPENSE'));});
$(document).on('click','.delete-expense',function(){const id=Number($(this).data('id'));if(!id||!confirm('Delete this expense record? This action cannot be undone.'))return;$.post('actions/expenses.php',{action:'delete',id:id},null,'json').done(r=>r.status==='success'?load():alert(r.message||'Unable to delete expense')).fail(()=>alert('Server error while deleting expense.'));});
$(document).on('click','.clear-btn',function(e){e.preventDefault();const type=$(this).data('type'),label=type==='month'?'this month':'this year';if(!confirm(`Clear all expense records for ${label} for this branch? This cannot be undone.`))return;$.post('actions/expenses.php',{action:type==='month'?'clear_month':'clear_year'},null,'json').done(r=>r.status==='success'?load():alert(r.message||'Unable to clear expenses')).fail(()=>alert('Server error while clearing expenses.'));});
$('#expenseSearch,#filterCategory,#filterStart,#filterEnd').on('input change',render);const t=today();$('#filterStart').val(t.slice(0,8)+'01');$('#filterEnd').val(t);load();})();
</script></body></html>
