<?php
declare(strict_types=1);ini_set('display_errors','0');error_reporting(E_ALL);if(session_status()===PHP_SESSION_NONE)session_start();date_default_timezone_set('Africa/Lusaka');header('Content-Type: application/json; charset=utf-8');require_once '../../includes/conn.php';require_once '../../includes/auth.php';
function out(array $x):void{echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
$p=(int)($_SESSION['pharmacy_id']??0);$b=(int)($_SESSION['branch_id']??0);$u=(int)($_SESSION['user_id']??0);if($p<=0||$b<=0){http_response_code(401);out(['status'=>'error','message'=>'Session expired.']);}$a=strtolower(trim((string)($_REQUEST['action']??'')));
if($a==='list'){$e=[];$total=0;$month=0;$cm=date('Y-m');$s=$conn->prepare('SELECT id,name,amount,expense_date,category,recorded_by,created_at FROM expenses WHERE pharmacy_id=? AND branch_id=? ORDER BY expense_date DESC,id DESC');if(!$s)out(['status'=>'error','message'=>'Unable to prepare expense list.']);$s->bind_param('ii',$p,$b);if(!$s->execute()){ $s->close();out(['status'=>'error','message'=>'Unable to load expenses.']);}$r=$s->get_result();while($x=$r->fetch_assoc()){$amt=(float)$x['amount'];$d=(string)$x['expense_date'];$e[]=['id'=>(int)$x['id'],'name'=>(string)$x['name'],'amount'=>$amt,'expense_date'=>$d,'category'=>(string)($x['category']??'General'),'recorded_by'=>(int)($x['recorded_by']??0),'created_at'=>(string)($x['created_at']??'')];$total+=$amt;if(substr($d,0,7)===$cm)$month+=$amt;}$s->close();out(['status'=>'success','expenses'=>$e,'total'=>round($total,2),'month_total'=>round($month,2),'count'=>count($e)]);}
if($_SERVER['REQUEST_METHOD']!=='POST')out(['status'=>'error','message'=>'Invalid request method.']);
if($a==='add'){$name=trim((string)($_POST['name']??''));$amount=(float)($_POST['amount']??0);$date=trim((string)($_POST['date']??''));$cat=trim((string)($_POST['category']??'General'));$allowed=['General','Utilities','Staff Welfare','Logistics','Stock/Supplies','Other'];if($name===''||mb_strlen($name)>150||$amount<=0||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))out(['status'=>'error','message'=>'Please provide valid expense details.']);if(!in_array($cat,$allowed,true))$cat='General';$amount=round($amount,2);$s=$conn->prepare('INSERT INTO expenses(pharmacy_id,branch_id,name,amount,expense_date,category,recorded_by) VALUES(?,?,?,?,?,?,?)');if(!$s)out(['status'=>'error','message'=>'Unable to prepare expense record.']);$s->bind_param('iisdssi',$p,$b,$name,$amount,$date,$cat,$u);if(!$s->execute()){ $s->close();out(['status'=>'error','message'=>'Unable to save expense.']);}$id=$s->insert_id;$s->close();out(['status'=>'success','message'=>'Expense recorded successfully.','id'=>(int)$id]);}
if($a==='delete'){$id=(int)($_POST['id']??0);if($id<=0)out(['status'=>'error','message'=>'Invalid expense record.']);$s=$conn->prepare('DELETE FROM expenses WHERE id=? AND pharmacy_id=? AND branch_id=?');if(!$s)out(['status'=>'error','message'=>'Unable to prepare delete operation.']);$s->bind_param('iii',$id,$p,$b);$s->execute();$n=$s->affected_rows;$s->close();if($n<1)out(['status'=>'error','message'=>'Expense not found or access denied.']);out(['status'=>'success','message'=>'Expense deleted successfully.']);}
if($a==='clear_month'||$a==='clear_year'){$start=$a==='clear_month'?date('Y-m-01'):date('Y-01-01');$next=$a==='clear_month'?date('Y-m-d',strtotime($start.' +1 month')):date('Y-m-d',strtotime($start.' +1 year'));$s=$conn->prepare('DELETE FROM expenses WHERE pharmacy_id=? AND branch_id=? AND expense_date>=? AND expense_date<?');if(!$s)out(['status'=>'error','message'=>'Unable to prepare clear operation.']);$s->bind_param('iiss',$p,$b,$start,$next);if(!$s->execute()){ $s->close();out(['status'=>'error','message'=>'Unable to clear expenses.']);}$n=$s->affected_rows;$s->close();out(['status'=>'success','message'=>($a==='clear_month'?'This month':'This year').' expense records were cleared.','deleted'=>$n]);}
out(['status'=>'error','message'=>'Unknown expense action.']);
