<?php
// Buffer output to catch any stray printed characters (like '1' from includes)
ob_start();

// Disable HTML error reporting to protect JSON integrity
ini_set('display_errors', 0);
error_reporting(E_ALL);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Enable MySQLi exception throwing for easy catching
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

// Correct absolute path navigation up to project root
$base_dir = dirname(__DIR__, 2);
$conn_path = $base_dir . '/includes/conn.php';
$auth_path = $base_dir . '/includes/auth.php';

if (file_exists($conn_path)) {
    require_once $conn_path;
}
if (file_exists($auth_path)) {
    require_once $auth_path;
}

// Clean out any output generated by includes (e.g., '1' or whitespace)
ob_clean();

header('Content-Type: application/json; charset=utf-8');

// Session validation
$pharmacy_id = (int)($_SESSION['pharmacy_id'] ?? 0);
$branch_id   = (int)($_SESSION['branch_id'] ?? 0);

if (!$pharmacy_id || !$branch_id) {
    echo json_encode([
        'status'  => 'error', 
        'message' => 'Session expired. Please log in again.'
    ]);
    exit();
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $invoice_number    = trim($_POST['invoice_number'] ?? '');
    $first_name        = trim($_POST['first_name'] ?? '');
    $last_name         = trim($_POST['last_name'] ?? '');
    $contact_number    = trim($_POST['contact_number'] ?? '');
    $patient_condation = trim($_POST['patient_condation'] ?? 'No');

    if (empty($first_name) || empty($last_name) || empty($contact_number)) {
        echo json_encode([
            'status'  => 'error', 
            'message' => 'Please fill in First Name, Last Name, and Phone Number.'
        ]);
        exit();
    }

    if (empty($invoice_number)) {
        $invoice_number = 'PAT-' . mt_rand(100000, 999999);
    }

    try {
        $stmt = $conn->prepare("INSERT INTO patients 
            (pharmacy_id, branch_id, invoice_number, first_name, last_name, contact_number, registration_date, status, patient_condation) 
            VALUES (?, ?, ?, ?, ?, ?, NOW(), 'Active', ?)");

        $stmt->bind_param("iisssss", 
            $pharmacy_id, 
            $branch_id, 
            $invoice_number, 
            $first_name, 
            $last_name, 
            $contact_number, 
            $patient_condation
        );

        $stmt->execute();
        $stmt->close();

        echo json_encode([
            'status'  => 'success', 
            'message' => 'Patient successfully registered! Ref: ' . $invoice_number
        ]);
        exit();

    } catch (Exception $e) {
        echo json_encode([
            'status'  => 'error', 
            'message' => 'Database Error: ' . $e->getMessage()
        ]);
        exit();
    }
} else {
    echo json_encode([
        'status'  => 'error', 
        'message' => 'Invalid Request Method.'
    ]);
    exit();
}
