<?php
/**
 * EchoTech POS - ZRA Smart Invoice / VSDC ZRA INTEGRATION
 * Admin-only integration control surface.
 * Location: /admin/actions/zra.php
 */
declare(strict_types=1);

if (session_status() === PHP_SESSION_NONE) {
    $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || ((int)($_SERVER['SERVER_PORT'] ?? 0) === 443);
    session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>$https,'httponly'=>true,'samesite'=>'Lax']);
    session_start();
}

foreach ([__DIR__.'/../../includes/auth.php', __DIR__.'/../../includes/auth_helpers.php', __DIR__.'/../../auth.php'] as $f) {
    if (is_file($f)) { require_once $f; break; }
}
foreach ([__DIR__.'/../../includes/conn.php', __DIR__.'/../../config.php', __DIR__.'/../../db.php'] as $f) {
    if (is_file($f)) { require_once $f; if (isset($conn) && $conn instanceof mysqli) break; }
}

if (function_exists('require_login')) require_login();
if ((string)($_SESSION['role'] ?? '') !== 'Admin') { http_response_code(403); exit('Access denied. ZRA Integration is restricted to Admin.'); }
if (!isset($conn) || !($conn instanceof mysqli)) { http_response_code(500); exit('Database connection unavailable.'); }
$conn->set_charset('utf8mb4');

require_once __DIR__.'/zra_client.php';

$pharmacyId = (int)($_SESSION['pharmacy_id'] ?? 0);
$userId = (int)($_SESSION['user_id'] ?? 0);
if ($pharmacyId <= 0) { http_response_code(400); exit('Pharmacy session is missing.'); }

function zra_admin_h(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function zra_admin_table(mysqli $db,string $name):bool { $name=$db->real_escape_string($name); $r=@$db->query("SHOW TABLES LIKE '{$name}'"); return $r instanceof mysqli_result && $r->num_rows>0; }
function zra_admin_setting(mysqli $db,int $pharmacyId):array { if(!zra_admin_table($db,'compliance_settings'))return[]; $s=$db->prepare('SELECT * FROM compliance_settings WHERE pharmacy_id=? LIMIT 1'); if(!$s)return[]; $s->bind_param('i',$pharmacyId); $s->execute();$r=$s->get_result();$x=$r?$r->fetch_assoc():[];$s->close();return $x?:[]; }
function zra_admin_redirect(string $msg='',string $err=''):never { $q=[];if($msg!=='')$q['ok']=$msg;if($err!=='')$q['err']=$err;header('Location: ../zra.php'.($q?'?'.http_build_query($q):''));exit; }
function zra_admin_audit(mysqli $db,int $pharmacyId,int $userId,string $action,string $desc=''):void { if(!zra_admin_table($db,'compliance_audit_log'))return; $ip=substr((string)($_SERVER['REMOTE_ADDR']??''),0,64);$s=$db->prepare('INSERT INTO compliance_audit_log (pharmacy_id,user_id,action,entity_type,description,ip_address) VALUES (?,?,?,?,?,?)');if($s){$type='zra_integration';$s->bind_param('iissss',$pharmacyId,$userId,$action,$type,$desc,$ip);@$s->execute();$s->close();} }
function zra_admin_csrf():void { if($_SERVER['REQUEST_METHOD']!=='POST')return; $token=(string)($_POST['csrf']??'');if(empty($_SESSION['zra_csrf'])||!hash_equals($_SESSION['zra_csrf'],$token)){http_response_code(419);exit('Invalid security token. Refresh and try again.');} }
function zra_admin_columns(mysqli $db,string $table):array { $out=[];$r=@$db->query('SHOW COLUMNS FROM `'.$db->real_escape_string($table).'`');if($r)while($x=$r->fetch_assoc())$out[]=$x['Field'];return$out; }
function zra_admin_branch_bhf(mysqli $db,int $pharmacyId,int $branchId):string {
    if(zra_admin_table($db,'compliance_branches')){
        $s=$db->prepare('SELECT zra_bhf_id FROM compliance_branches WHERE pharmacy_id=? AND branch_id=? LIMIT 1');
        if($s){$s->bind_param('ii',$pharmacyId,$branchId);$s->execute();$r=$s->get_result();$x=$r?$r->fetch_assoc():[];$s->close();if(!empty($x['zra_bhf_id'])&&preg_match('/^.{3}$/',(string)$x['zra_bhf_id']))return trim((string)$x['zra_bhf_id']);}
    }
    return '';
}
function zra_admin_device(mysqli $db,int $pharmacyId,int $branchId,string $env):array { $s=$db->prepare('SELECT * FROM zra_devices WHERE pharmacy_id=? AND branch_id=? AND environment=? LIMIT 1');if(!$s)return[];$s->bind_param('iis',$pharmacyId,$branchId,$env);$s->execute();$r=$s->get_result();$x=$r?$r->fetch_assoc():[];$s->close();return$x?:[]; }
function zra_admin_log_api(mysqli $db,int $pharmacyId,int $branchId,?int $queueId,string $endpoint,array $res,array $request):void { if(!zra_admin_table($db,'zra_api_log'))return;$body=json_encode($request,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$resp=(string)($res['body']??'');$http=(int)($res['http_status']??0);$dur=(int)($res['duration_ms']??0);$s=$db->prepare('INSERT INTO zra_api_log (pharmacy_id,branch_id,queue_id,endpoint,http_status,request_body,response_body,duration_ms) VALUES (?,?,?,?,?,?,?,?)');if($s){$s->bind_param('iiissssi',$pharmacyId,$branchId,$queueId,$endpoint,$http,$body,$resp,$dur);@$s->execute();$s->close();} }
zra_admin_csrf();
if(empty($_SESSION['zra_csrf']))$_SESSION['zra_csrf']=bin2hex(random_bytes(24));

$settings=zra_admin_setting($conn,$pharmacyId);
$env=(string)($settings['smart_invoice_environment']??'test');if(!in_array($env,['test','production'],true))$env='test';
$baseUrl=trim((string)($settings['vsdc_endpoint']??''));

if($_SERVER['REQUEST_METHOD']==='POST'){
    $action=trim((string)($_POST['action']??''));

    if($action==='save_branch'){
        if(!zra_admin_table($conn,'compliance_branches'))zra_admin_redirect('', 'Run compliance SQL first.');
        $branchId=(int)($_POST['branch_id']??0);$bhf=trim((string)($_POST['zra_bhf_id']??''));
        if(!preg_match('/^.{3}$/',$bhf))zra_admin_redirect('', 'ZRA Branch ID (bhfId) must be exactly 3 characters.');
        $chk=$conn->prepare('SELECT id,branch_name FROM branches WHERE id=? AND pharmacy_id=? LIMIT 1');if(!$chk)zra_admin_redirect('', 'Unable to validate branch.');$chk->bind_param('ii',$branchId,$pharmacyId);$chk->execute();$br=$chk->get_result()->fetch_assoc();$chk->close();if(!$br)zra_admin_redirect('', 'The branch does not belong to this pharmacy.');
        $name=(string)$br['branch_name'];
        $existingId=0;$find=$conn->prepare('SELECT id FROM compliance_branches WHERE pharmacy_id=? AND branch_id=? ORDER BY id DESC LIMIT 1');
        if($find){$find->bind_param('ii',$pharmacyId,$branchId);$find->execute();$row=$find->get_result()->fetch_assoc();$existingId=(int)($row['id']??0);$find->close();}
        if($existingId>0){$s=$conn->prepare('UPDATE compliance_branches SET branch_name=?,zra_bhf_id=?,updated_by=? WHERE id=? AND pharmacy_id=?');if(!$s)zra_admin_redirect('', 'Unable to prepare branch mapping.');$s->bind_param('ssiii',$name,$bhf,$userId,$existingId,$pharmacyId);$ok=$s->execute();$s->close();}
        else{$s=$conn->prepare('INSERT INTO compliance_branches (pharmacy_id,branch_id,branch_name,zra_bhf_id,updated_by) VALUES (?,?,?,?,?)');if(!$s)zra_admin_redirect('', 'Unable to prepare branch mapping.');$s->bind_param('iissi',$pharmacyId,$branchId,$name,$bhf,$userId);$ok=$s->execute();$s->close();}
        if(!$ok)zra_admin_redirect('', 'Branch mapping could not be saved.');zra_admin_audit($conn,$pharmacyId,$userId,'zra_branch_mapping','Mapped '.$name.' to ZRA bhfId '.$bhf);zra_admin_redirect('Branch mapping saved.');
    }

    if($action==='initialize_device'){
        $branchId=(int)($_POST['branch_id']??0);$serial=trim((string)($_POST['device_serial']??''));$bhf=trim((string)($_POST['bhf_id']??''));$base=trim((string)($_POST['base_url']??$baseUrl));
        if($branchId<=0||$serial===''||$base===''||!preg_match('/^.{3}$/',$bhf))zra_admin_redirect('', 'Branch, device serial, VSDC/OSDC URL and 3-character bhfId are required.');
        $tpin=preg_replace('/\D+/','',(string)($settings['tpin']??''));if(strlen($tpin)!==10)zra_admin_redirect('', 'Enter the 10-digit ZRA TPIN in Compliance before initialization.');
        try{
            $res=zra_http_post($base,'/initializer/selectInitInfo',['tpin'=>$tpin,'bhfId'=>$bhf,'dvcSrlNo'=>$serial]);
            zra_admin_log_api($conn,$pharmacyId,$branchId,null,'/initializer/selectInitInfo',$res,['tpin'=>$tpin,'bhfId'=>$bhf,'dvcSrlNo'=>$serial]);
            if(!$res['ok'])zra_admin_redirect('', 'ZRA initialization failed: '.($res['error']??'Unknown error.'));
            $info=(array)($res['json']['data']['info']??$res['json']['data']??[]);
            $cmc=(string)($info['cmcKey']??'');$intrl=(string)($info['intrlKey']??'');$sign=(string)($info['signKey']??'');
            if($cmc===''||$intrl===''||$sign==='')throw new RuntimeException('Initialization response did not contain cmcKey, intrlKey and signKey.');
            $device=zra_admin_device($conn,$pharmacyId,$branchId,$env);$cmcEnc=zra_encrypt_secret($cmc);$intrlEnc=zra_encrypt_secret($intrl);$signEnc=zra_encrypt_secret($sign);$deviceId=(string)($info['dvcId']??'');$sdc=(string)($info['sdcId']??$info['sdicId']??'');$mrc=(string)($info['mrcNo']??'');$lastSale=(int)($info['lastSaleInvcNo']??0);$lastRcpt=(int)($info['lastSaleRcptNo']??0);$lastInv=(int)($info['lastInvcNo']??0);
            $sql='INSERT INTO zra_devices (pharmacy_id,branch_id,bhf_id,device_serial,environment,base_url,initialized,device_id,sdc_id,mrc_no,cmc_key_enc,intrl_key_enc,sign_key_enc,last_sale_invc_no,last_sale_rcpt_no,last_invc_no,last_init_at,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?,?) ON DUPLICATE KEY UPDATE bhf_id=VALUES(bhf_id),device_serial=VALUES(device_serial),base_url=VALUES(base_url),initialized=VALUES(initialized),device_id=VALUES(device_id),sdc_id=VALUES(sdc_id),mrc_no=VALUES(mrc_no),cmc_key_enc=VALUES(cmc_key_enc),intrl_key_enc=VALUES(intrl_key_enc),sign_key_enc=VALUES(sign_key_enc),last_sale_invc_no=VALUES(last_sale_invc_no),last_sale_rcpt_no=VALUES(last_sale_rcpt_no),last_invc_no=VALUES(last_invc_no),last_init_at=NOW(),last_error=NULL,updated_by=VALUES(updated_by)';
            $s=$conn->prepare($sql);if(!$s)throw new RuntimeException('Unable to save initialized device: '.$conn->error);$one=1;$s->bind_param('iissssissssssiiiii',$pharmacyId,$branchId,$bhf,$serial,$env,$base,$one,$deviceId,$sdc,$mrc,$cmcEnc,$intrlEnc,$signEnc,$lastSale,$lastRcpt,$lastInv,$userId,$userId);$s->execute();$s->close();
            zra_admin_audit($conn,$pharmacyId,$userId,'zra_device_initialized','Initialized ZRA device for branch '.$branchId.' in '.$env.' environment.');zra_admin_redirect('ZRA device initialized successfully.');
        }catch(Throwable $e){zra_admin_redirect('', $e->getMessage());}
    }

    if($action==='sync_codes' || $action==='sync_classes'){
        $branchId=(int)($_POST['branch_id']??0);$bhf=trim((string)($_POST['bhf_id']??''));
        $device=zra_admin_device($conn,$pharmacyId,$branchId,$env);$base=trim((string)($device['base_url']??$baseUrl));$tpin=preg_replace('/\D+/','',(string)($settings['tpin']??''));
        if(!$device || (int)($device['initialized'])!==1)zra_admin_redirect('', 'Initialize the ZRA device before synchronizing reference data.');
        if(strlen($tpin)!==10||!preg_match('/^.{3}$/',$bhf))zra_admin_redirect('', 'Valid TPIN and ZRA branch ID are required.');
        $endpoint=$action==='sync_codes'?'/code/selectCodes':'/itemClass/selectItemsClass';
        $payload=['tpin'=>$tpin,'bhfId'=>$bhf,'lastReqDt'=>'20231215000000'];
        $res=zra_http_post($base,$endpoint,$payload);zra_admin_log_api($conn,$pharmacyId,$branchId,null,$endpoint,$res,$payload);
        if(!$res['ok'])zra_admin_redirect('', 'Reference-data sync failed: '.($res['error']??'Unknown error.'));
        $data=(array)($res['json']['data']??[]);
        if($action==='sync_codes'){
            $classes=(array)($data['clsList']??[]);$count=0;
            foreach($classes as $class){$cc=(string)($class['cdCls']??'');$cn=(string)($class['cdClsNm']??'');foreach((array)($class['dtlList']??[]) as $d){$code=(string)($d['cd']??'');if($cc===''||$code==='')continue;$s=$conn->prepare('INSERT INTO zra_standard_codes (pharmacy_id,branch_id,code_class,code_class_name,code,code_name,user_defined_name,last_sync_at) VALUES (?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE code_class_name=VALUES(code_class_name),code_name=VALUES(code_name),user_defined_name=VALUES(user_defined_name),last_sync_at=NOW()');if($s){$ud=(string)($d['userDfnNm1']??'');$s->bind_param('iisssss',$pharmacyId,$branchId,$cc,$cn,$code,$d['cdNm'],$ud);@$s->execute();$s->close();$count++;}}}
        }else{
            $list=(array)($data['itemClsList']??[]);$count=0;foreach($list as $item){$code=(string)($item['itemClsCd']??'');if($code==='')continue;$s=$conn->prepare('INSERT INTO zra_item_classes (pharmacy_id,branch_id,item_cls_cd,item_cls_nm,item_cls_lvl,last_sync_at) VALUES (?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE item_cls_nm=VALUES(item_cls_nm),item_cls_lvl=VALUES(item_cls_lvl),last_sync_at=NOW()');if($s){$name=(string)($item['itemClsNm']??'');$lvl=(int)($item['itemClsLvl']??0);$s->bind_param('iissi',$pharmacyId,$branchId,$code,$name,$lvl);@$s->execute();$s->close();$count++;}}
        }
        zra_admin_audit($conn,$pharmacyId,$userId,$action,'Synchronized ZRA reference data for branch '.$branchId.'.');zra_admin_redirect('Reference data synchronized.');
    }

    if($action==='queue_sale'){
        $saleId=(int)($_POST['sale_id']??0);$branchId=(int)($_POST['branch_id']??0);$bhf=trim((string)($_POST['bhf_id']??''));
        if($saleId<=0||$branchId<=0||!preg_match('/^.{3}$/',$bhf))zra_admin_redirect('', 'Sale, branch and ZRA branch ID are required.');
        $saleStmt=$conn->prepare('SELECT * FROM sales WHERE id=? AND pharmacy_id=? AND branch_id=? LIMIT 1');if(!$saleStmt)zra_admin_redirect('', 'Unable to prepare sale lookup.');$saleStmt->bind_param('iii',$saleId,$pharmacyId,$branchId);$saleStmt->execute();$sale=$saleStmt->get_result()->fetch_assoc();$saleStmt->close();if(!$sale)zra_admin_redirect('', 'Sale was not found in this pharmacy/branch.');
        $itemStmt=$conn->prepare('SELECT si.product_id,si.quantity,si.unit_price,st.item_name,st.tax_rate,st.barcode,st.zra_item_cd,st.zra_item_cls_cd,st.zra_pkg_unit_cd,st.zra_qty_unit_cd,st.zra_tax_type_cd FROM sales_items si INNER JOIN store_items st ON st.id=si.product_id WHERE si.sale_id=? AND si.pharmacy_id=? AND si.branch_id=? ORDER BY si.id');if(!$itemStmt)zra_admin_redirect('', 'Unable to prepare sale items lookup.');$itemStmt->bind_param('iii',$saleId,$pharmacyId,$branchId);$itemStmt->execute();$rr=$itemStmt->get_result();$items=[];while($x=$rr->fetch_assoc())$items[]=$x;$itemStmt->close();
        try{$payload=zra_build_sale_payload($sale,$items,$settings,$bhf);}catch(Throwable $e){zra_admin_redirect('', $e->getMessage());}
        $ref='SALE:'.$pharmacyId.':'.$branchId.':'.$saleId;$json=json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$s=$conn->prepare('INSERT INTO zra_queue (pharmacy_id,branch_id,sale_id,local_reference,endpoint,payload,status,next_attempt_at,created_by) VALUES (?,?,?,?,?,? ,"queued",NOW(),?) ON DUPLICATE KEY UPDATE sale_id=VALUES(sale_id),payload=VALUES(payload),endpoint=VALUES(endpoint),status=IF(status IN ("submitted"),status,"queued"),updated_at=NOW()');if(!$s)zra_admin_redirect('', 'Unable to create ZRA queue record.');$endpoint='/trnsSales/saveSales';$s->bind_param('iiisssi',$pharmacyId,$branchId,$saleId,$ref,$endpoint,$json,$userId);$ok=$s->execute();$s->close();if(!$ok)zra_admin_redirect('', 'Unable to queue sale.');zra_admin_audit($conn,$pharmacyId,$userId,'zra_sale_queued','Queued POS sale '.$saleId.' for ZRA submission.');zra_admin_redirect('Sale queued for ZRA submission.');
    }

    if($action==='submit_queue'){
        $queueId=(int)($_POST['queue_id']??0);$q=$conn->prepare('SELECT * FROM zra_queue WHERE id=? AND pharmacy_id=? LIMIT 1');if(!$q)zra_admin_redirect('', 'Unable to prepare queue lookup.');$q->bind_param('ii',$queueId,$pharmacyId);$q->execute();$row=$q->get_result()->fetch_assoc();$q->close();if(!$row)zra_admin_redirect('', 'Queue record not found.');
        $device=zra_admin_device($conn,$pharmacyId,(int)$row['branch_id'],$env);if(!$device||(int)$device['initialized']!==1)zra_admin_redirect('', 'The branch device is not initialized.');$payload=json_decode((string)$row['payload'],true);if(!is_array($payload))zra_admin_redirect('', 'Queue payload is invalid.');
        $endpoint=(string)$row['endpoint'];$base=trim((string)$device['base_url']);$up=$conn->prepare('UPDATE zra_queue SET status="processing",attempts=attempts+1,last_attempt_at=NOW() WHERE id=? AND pharmacy_id=?');if($up){$up->bind_param('ii',$queueId,$pharmacyId);$up->execute();$up->close();}
        $res=zra_http_post($base,$endpoint,$payload);zra_admin_log_api($conn,$pharmacyId,(int)$row['branch_id'],$queueId,$endpoint,$res,$payload);
        $j=$res['json'];$code=is_array($j)?(string)($j['resultCd']??''):'';$msg=is_array($j)?(string)($j['resultMsg']??''):($res['error']??'');$status=$res['ok']?'submitted':(($res['http_status']>=400&&$res['http_status']<500)?'rejected':'failed');$resp=(string)($res['body']??'');
        $s=$conn->prepare('UPDATE zra_queue SET status=?,http_status=?,result_code=?,result_message=?,response_payload=?,submitted_at=IF(?="submitted",NOW(),submitted_at),next_attempt_at=IF(?="failed",DATE_ADD(NOW(),INTERVAL LEAST(attempts*5,60) MINUTE),NULL) WHERE id=? AND pharmacy_id=?');if($s){$s->bind_param('sisssssii',$status,$res['http_status'],$code,$msg,$resp,$status,$status,$queueId,$pharmacyId);@$s->execute();$s->close();}
        if($res['ok'] && (int)$row['sale_id']>0){$data=(array)($j['data']??[]);$rcpt=(string)($data['rcptNo']??'');$intrl=(string)($data['intrlData']??'');$sign=(string)($data['rcptSign']??'');$qr=(string)($data['qrCodeUrl']??'');if(zra_admin_table($conn,'compliance_invoices')){$s=$conn->prepare('UPDATE compliance_invoices SET status="accepted",zra_invoice_no=?,zra_sdc_id=?,zra_signature=?,zra_internal_data=?,response_message=?,response_payload=?,submitted_at=NOW(),queue_id=?,rcpt_no=?,intrl_data=?,rcpt_sign=?,qr_code_url=? WHERE sale_id=? AND pharmacy_id=?');if($s){$responseMsg=$msg;$s->bind_param('ssssssissssii',$rcpt,(string)($device['sdc_id']??''),$sign,$intrl,$responseMsg,$resp,$queueId,$rcpt,$intrl,$sign,$qr,(int)$row['sale_id'],$pharmacyId);@$s->execute();$s->close();}}
        }
        if($res['ok'])zra_admin_redirect('Sale submitted successfully to the configured ZRA controller.');zra_admin_redirect('', 'ZRA submission failed: '.$msg);
    }

    if($action==='select_invoice'){
        $branchId=(int)($_POST['branch_id']??0);$bhf=trim((string)($_POST['bhf_id']??''));$sdc=trim((string)($_POST['sdc_id']??''));$cis=trim((string)($_POST['cis_invoice']??''));$device=zra_admin_device($conn,$pharmacyId,$branchId,$env);if(!$device||(int)$device['initialized']!==1)zra_admin_redirect('', 'Initialize the branch device first.');$tpin=preg_replace('/\D+/','',(string)($settings['tpin']??''));$payload=['tpin'=>$tpin,'bhfId'=>$bhf,'invcSdcId'=>$sdc,'cisInvcNo'=>$cis];$res=zra_http_post((string)$device['base_url'],'/trnsSales/selectInvoice',$payload);zra_admin_log_api($conn,$pharmacyId,$branchId,null,'/trnsSales/selectInvoice',$res,$payload);if(!$res['ok'])zra_admin_redirect('', 'Invoice lookup failed: '.($res['error']??'Unknown error.'));$_SESSION['zra2_last_lookup']=$res['json'];zra_admin_redirect('ZRA invoice lookup completed.');
    }
}

$ok=(string)($_GET['ok']??'');$err=(string)($_GET['err']??'');
$branches=[];$s=$conn->prepare('SELECT id,branch_name FROM branches WHERE pharmacy_id=? ORDER BY branch_name');if($s){$s->bind_param('i',$pharmacyId);$s->execute();$r=$s->get_result();while($r&&($x=$r->fetch_assoc()))$branches[]=$x;$s->close();}
$devices=[];$s=$conn->prepare('SELECT d.*,b.branch_name FROM zra_devices d LEFT JOIN branches b ON b.id=d.branch_id AND b.pharmacy_id=d.pharmacy_id WHERE d.pharmacy_id=? ORDER BY b.branch_name');if($s){$s->bind_param('i',$pharmacyId);$s->execute();$r=$s->get_result();while($r&&($x=$r->fetch_assoc()))$devices[]=$x;$s->close();}
$queue=[];$s=$conn->prepare('SELECT q.*,b.branch_name FROM zra_queue q LEFT JOIN branches b ON b.id=q.branch_id AND b.pharmacy_id=q.pharmacy_id WHERE q.pharmacy_id=? ORDER BY q.id DESC LIMIT 100');if($s){$s->bind_param('i',$pharmacyId);$s->execute();$r=$s->get_result();while($r&&($x=$r->fetch_assoc()))$queue[]=$x;$s->close();}
$recentSales=[];$s=$conn->prepare('SELECT id,branch_id,invoice,created_at,total,payment_method FROM sales WHERE pharmacy_id=? ORDER BY id DESC LIMIT 50');if($s){$s->bind_param('i',$pharmacyId);$s->execute();$r=$s->get_result();while($r&&($x=$r->fetch_assoc()))$recentSales[]=$x;$s->close();}
$classesCount=0;$codesCount=0;if(zra_admin_table($conn,'zra_item_classes')){$s=$conn->prepare('SELECT COUNT(*) c FROM zra_item_classes WHERE pharmacy_id=?');if($s){$s->bind_param('i',$pharmacyId);$s->execute();$x=$s->get_result()->fetch_assoc();$classesCount=(int)($x['c']??0);$s->close();}}if(zra_admin_table($conn,'zra_standard_codes')){$s=$conn->prepare('SELECT COUNT(*) c FROM zra_standard_codes WHERE pharmacy_id=?');if($s){$s->bind_param('i',$pharmacyId);$s->execute();$x=$s->get_result()->fetch_assoc();$codesCount=(int)($x['c']??0);$s->close();}}
$current_admin_page='zra.php';$admin_page_title='ZRA Smart Invoice — ZRA Integration';$user_display_name=(string)($_SESSION['full_name']??$_SESSION['username']??'Administrator');$adminAside=__DIR__.'/../admin_aside.php';$adminHeader=__DIR__.'/../admin_header.php';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ZRA Smart Invoice — ZRA Integration</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><style>
:root{--bg:#f4f6f9;--card:#fff;--text:#17202b;--muted:#718096;--border:#e3e8ef;--blue:#2563eb;--green:#059669;--red:#dc2626;--orange:#d97706;--shadow:0 4px 18px rgba(15,23,42,.06)}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.main{min-height:100vh}.wrap{padding:24px;max-width:1600px;margin:auto}.head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:18px}.head h1{margin:0 0 5px;font-size:28px}.muted{color:var(--muted)}.btn{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--border);background:#fff;color:var(--text);padding:9px 13px;border-radius:8px;text-decoration:none;font-weight:800;cursor:pointer}.btn.primary{background:var(--blue);border-color:var(--blue);color:#fff}.btn.green{background:var(--green);border-color:var(--green);color:#fff}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.card,.panel{background:#fff;border:1px solid var(--border);border-radius:12px;box-shadow:var(--shadow)}.card{padding:16px}.label{font-size:11px;text-transform:uppercase;color:var(--muted);font-weight:900}.value{font-size:26px;font-weight:900;margin-top:7px}.panel{overflow:hidden;margin-bottom:16px}.panel h2{font-size:17px;margin:0}.ph{padding:16px 18px;border-bottom:1px solid var(--border)}.pb{padding:18px}.alert{padding:12px 14px;border-radius:9px;margin-bottom:14px}.ok{background:#ecfdf5;color:#047857;border:1px solid #a7f3d0}.err{background:#fef2f2;color:#b91c1c;border:1px solid #fecaca}.fields{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.field{margin-bottom:11px}.field label{display:block;font-size:12px;font-weight:900;margin-bottom:6px}.field input,.field select{width:100%;padding:10px;border:1px solid #d9e0e8;border-radius:8px;font:inherit;background:#fff}.actions{display:flex;gap:8px;flex-wrap:wrap}.notice{padding:12px;border:1px solid #dbe5f3;background:#f7faff;border-radius:8px;color:#40566f;line-height:1.5;font-size:12px;margin-bottom:12px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #edf0f4;text-align:left;font-size:12px}th{font-size:10px;text-transform:uppercase;color:#667789;background:#fafbfc}.badge{display:inline-block;padding:5px 8px;border-radius:999px;font-size:10px;font-weight:900}.bgreen{background:#eaf8f1;color:#047857}.borange{background:#fff7e6;color:#b45309}.bred{background:#fef0f0;color:#b91c1c}.bgray{background:#eef2f5;color:#5b6773}@media(max-width:1000px){.grid{grid-template-columns:repeat(2,1fr)}.fields{grid-template-columns:1fr}}@media(max-width:600px){.wrap{padding:14px}.grid{grid-template-columns:1fr}.head{flex-direction:column}.head h1{font-size:23px}}
</style></head><body><div class="app"><?php if(is_file($adminAside))require $adminAside; ?><main class="main"><?php if(is_file($adminHeader))require $adminHeader; ?><div class="wrap">
<div class="head"><div><div style="color:#2563eb;font-size:11px;font-weight:900;letter-spacing:.08em;text-transform:uppercase">Administration / ZRA</div><h1>Smart Invoice — ZRA Integration</h1><p class="muted">VSDC/OSDC integration, device initialization, reference data and controlled invoice submission.</p></div><div class="actions"><a class="btn" href="compliance.php"><i class="fa-solid fa-arrow-left"></i> Compliance</a><a class="btn primary" href="https://www.zra.org.zm/smart-invoice-learn-more/" target="_blank" rel="noopener"><i class="fa-solid fa-landmark"></i> ZRA</a></div></div>
<?php if($ok):?><div class="alert ok"><i class="fa-solid fa-circle-check"></i> <?=zra_admin_h($ok)?></div><?php endif;?><?php if($err):?><div class="alert err"><i class="fa-solid fa-circle-exclamation"></i> <?=zra_admin_h($err)?></div><?php endif;?>
<div class="grid"><div class="card"><div class="label">Environment</div><div class="value"><?=zra_admin_h(ucfirst($env))?></div><div class="muted">Configured in Compliance</div></div><div class="card"><div class="label">Devices</div><div class="value"><?=count($devices)?></div><div class="muted">Branch controllers</div></div><div class="card"><div class="label">Standard Codes</div><div class="value"><?=$codesCount?></div><div class="muted">Locally stored</div></div><div class="card"><div class="label">Classification Codes</div><div class="value"><?=$classesCount?></div><div class="muted">Locally stored</div></div></div>
<div class="panel"><div class="ph"><h2>ZRA Integration safety boundary</h2></div><div class="pb"><div class="notice"><b>Important:</b> ZRA Integration supports the official ZRA VSDC/OSDC interface, but live production transmission must only be enabled after the taxpayer/device has been approved and the EchoTech POS solution has completed the applicable ZRA integration/certification process. ZRA's current documentation identifies the VSDC as the bridge for certified third-party invoicing systems.</div><div class="notice">The controller is responsible for device initialization and signing. EchoTech stores encrypted device credentials and sends JSON requests to the configured controller. No ZRA private key is displayed in this page.</div></div></div>
<div class="panel"><div class="ph"><h2>1. Branch / ZRA device setup</h2></div><div class="pb"><form method="post"><input type="hidden" name="csrf" value="<?=zra_admin_h($_SESSION['zra_csrf'])?>"><input type="hidden" name="action" value="save_branch"><div class="fields"><div class="field"><label>POS Branch</label><select name="branch_id" required><option value="">Select branch</option><?php foreach($branches as $b):?><option value="<?=$b['id']?>"><?=zra_admin_h($b['branch_name'])?></option><?php endforeach;?></select></div><div class="field"><label>ZRA Branch ID (bhfId)</label><input name="zra_bhf_id" maxlength="3" required placeholder="000"></div></div><button class="btn primary"><i class="fa-solid fa-link"></i> Save Branch Mapping</button></form></div></div>
<div class="panel"><div class="ph"><h2>2. Initialize VSDC / OSDC device</h2><p class="muted">ZRA requires TPIN, 3-character branch ID and device serial for initialization.</p></div><div class="pb"><form method="post"><input type="hidden" name="csrf" value="<?=zra_admin_h($_SESSION['zra_csrf'])?>"><input type="hidden" name="action" value="initialize_device"><div class="fields"><div class="field"><label>Branch</label><select name="branch_id" id="initBranch" required onchange="setBhf(this)"><option value="">Select branch</option><?php foreach($branches as $b):?><option value="<?=$b['id']?>"><?=zra_admin_h($b['branch_name'])?></option><?php endforeach;?></select></div><div class="field"><label>ZRA bhfId</label><input name="bhf_id" id="bhf" maxlength="3" required placeholder="000"></div><div class="field"><label>Device Serial Number</label><input name="device_serial" maxlength="100" required></div><div class="field"><label>VSDC / OSDC Base URL</label><input name="base_url" value="<?=zra_admin_h($baseUrl)?>" required placeholder="http://localhost:8080/zraVsdc..."></div></div><button class="btn green"><i class="fa-solid fa-plug"></i> Initialize Device</button></form></div></div>
<div class="panel"><div class="ph"><h2>3. Reference data</h2><p class="muted">ZRA requires standard codes and classification codes to be stored locally before transaction/item integration.</p></div><div class="pb"><div class="fields"><form method="post"><input type="hidden" name="csrf" value="<?=zra_admin_h($_SESSION['zra_csrf'])?>"><input type="hidden" name="action" value="sync_codes"><div class="field"><label>Branch</label><select name="branch_id" required><option value="">Select branch</option><?php foreach($devices as $d):?><option value="<?=zra_admin_h($d['branch_id'])?>"><?=zra_admin_h($d['branch_name']??$d['branch_id'])?> — <?=zra_admin_h($d['bhf_id'])?></option><?php endforeach;?></select></div><div class="field"><label>bhfId</label><input name="bhf_id" maxlength="3" required></div><button class="btn"><i class="fa-solid fa-arrows-rotate"></i> Sync Standard Codes</button></form><form method="post"><input type="hidden" name="csrf" value="<?=zra_admin_h($_SESSION['zra_csrf'])?>"><input type="hidden" name="action" value="sync_classes"><div class="field"><label>Branch</label><select name="branch_id" required><option value="">Select branch</option><?php foreach($devices as $d):?><option value="<?=zra_admin_h($d['branch_id'])?>"><?=zra_admin_h($d['branch_name']??$d['branch_id'])?> — <?=zra_admin_h($d['bhf_id'])?></option><?php endforeach;?></select></div><div class="field"><label>bhfId</label><input name="bhf_id" maxlength="3" required></div><button class="btn"><i class="fa-solid fa-list"></i> Sync Classification Codes</button></form></div></div></div>
<div class="panel"><div class="ph"><h2>Configured devices</h2></div><div class="pb" style="overflow:auto"><table><thead><tr><th>Branch</th><th>bhfId</th><th>Environment</th><th>Device</th><th>SDC</th><th>Status</th></tr></thead><tbody><?php if(!$devices):?><tr><td colspan="6" class="muted">No ZRA devices initialized.</td></tr><?php else:foreach($devices as $d):?><tr><td><?=zra_admin_h($d['branch_name']??$d['branch_id'])?></td><td><?=zra_admin_h($d['bhf_id'])?></td><td><?=zra_admin_h($d['environment'])?></td><td><?=zra_admin_h($d['device_serial'])?></td><td><?=zra_admin_h($d['sdc_id']??'-')?></td><td><span class="badge <?=((int)$d['initialized']===1)?'bgreen':'bred'?>"><?=((int)$d['initialized']===1)?'Initialized':'Not initialized'?></span></td></tr><?php endforeach;endif;?></tbody></table></div></div>
<div class="panel"><div class="ph"><h2>4. POS sales submission queue</h2><p class="muted">Sales are built from the authoritative EchoTech sales/sales_items records and are isolated by pharmacy and branch.</p></div><div class="pb"><form method="post" class="fields" style="margin-bottom:15px"><input type="hidden" name="csrf" value="<?=zra_admin_h($_SESSION['zra_csrf'])?>"><input type="hidden" name="action" value="queue_sale"><div class="field"><label>Recent Sale</label><select name="sale_id" required><?php foreach($recentSales as $s):?><option value="<?=$s['id']?>">#<?=$s['id']?> — <?=zra_admin_h($s['invoice'])?> — K<?=number_format((float)$s['total'],2)?> — <?=zra_admin_h($s['payment_method'])?></option><?php endforeach;?></select></div><div class="field"><label>Branch / ZRA bhfId</label><select name="branch_id" required onchange="setQueueBhf(this)"><option value="">Select branch</option><?php foreach($branches as $b):?><option value="<?=$b['id']?>"><?=zra_admin_h($b['branch_name'])?></option><?php endforeach;?></select><input name="bhf_id" id="queueBhf" maxlength="3" required placeholder="000" style="margin-top:7px"></div><div><button class="btn primary" style="margin-top:24px"><i class="fa-solid fa-layer-group"></i> Queue Sale</button></div></form><div style="overflow:auto"><table><thead><tr><th>ID</th><th>Sale</th><th>Branch</th><th>Endpoint</th><th>Status</th><th>Attempts</th><th>Action</th></tr></thead><tbody><?php if(!$queue):?><tr><td colspan="7" class="muted">No queued ZRA transactions.</td></tr><?php else:foreach($queue as $q):?><tr><td><?=$q['id']?></td><td><?=zra_admin_h($q['local_reference'])?></td><td><?=zra_admin_h($q['branch_name']??$q['branch_id'])?></td><td><?=zra_admin_h($q['endpoint'])?></td><td><span class="badge <?=in_array($q['status'],['submitted'])?'bgreen':(in_array($q['status'],['rejected','failed'])?'bred':'borange')?>"><?=zra_admin_h($q['status'])?></span></td><td><?=$q['attempts']?></td><td><?php if(in_array($q['status'],['queued','failed','rejected'])):?><form method="post"><input type="hidden" name="csrf" value="<?=zra_admin_h($_SESSION['zra_csrf'])?>"><input type="hidden" name="action" value="submit_queue"><input type="hidden" name="queue_id" value="<?=$q['id']?>"><button class="btn green">Submit</button></form><?php else:?>-<?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div>
<div class="panel"><div class="ph"><h2>5. ZRA invoice verification</h2><p class="muted">Retrieve an invoice already posted to the configured controller.</p></div><div class="pb"><form method="post" class="fields"><input type="hidden" name="csrf" value="<?=zra_admin_h($_SESSION['zra_csrf'])?>"><input type="hidden" name="action" value="select_invoice"><div class="field"><label>Branch</label><select name="branch_id" required><option value="">Select branch</option><?php foreach($branches as $b):?><option value="<?=$b['id']?>"><?=zra_admin_h($b['branch_name'])?></option><?php endforeach;?></select></div><div class="field"><label>bhfId</label><input name="bhf_id" maxlength="3" required></div><div class="field"><label>SDC ID</label><input name="sdc_id" required></div><div class="field"><label>CIS Invoice Number</label><input name="cis_invoice" required></div><div><button class="btn"><i class="fa-solid fa-magnifying-glass"></i> Verify Invoice</button></div></form></div></div>
</div></main></div><script>
function setBhf(s){document.getElementById('bhf').value='';}
function setQueueBhf(s){document.getElementById('queueBhf').value='';}
</script></body></html>
