<?php
declare(strict_types=1);
if(session_status()===PHP_SESSION_NONE)session_start();
date_default_timezone_set('Africa/Lusaka');
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../includes/conn.php';

function out(bool $ok,string $message='',array $extra=[]):never{echo json_encode(array_merge(['success'=>$ok,'status'=>$ok?'success':'error','message'=>$message],$extra),JSON_UNESCAPED_SLASHES);exit;}
function csrf():void{if(!hash_equals((string)($_SESSION['online_cart_csrf']??''),(string)($_POST['csrf']??'')))out(false,'Security token expired. Please refresh the page and try again.');}
function branch(mysqli $db,int $id):array{ $s=$db->prepare('SELECT id,pharmacy_id,branch_name FROM branches WHERE id=? AND is_active=1 LIMIT 1');if(!$s)throw new RuntimeException('Unable to verify branch.');$s->bind_param('i',$id);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();if(!$r)throw new RuntimeException('The selected branch is unavailable.');return $r; }
function cart(int $bid):array{if(!isset($_SESSION['carts'])||!is_array($_SESSION['carts']))$_SESSION['carts']=[];if(!isset($_SESSION['carts'][$bid])||!is_array($_SESSION['carts'][$bid]))$_SESSION['carts'][$bid]=[];return $_SESSION['carts'][$bid];}
function summary(array $c):array{$n=0;$s=0;foreach($c as $x){$q=max(0,(int)($x['qty']??0));$n+=$q;$s+=(float)($x['price']??0)*$q;}return['items'=>array_values($c),'cart_count'=>$n,'subtotal'=>round($s,2),'total'=>round($s,2)];}
function product(mysqli $db,int $pid,int $bid,bool $lock=false):?array{$sql='SELECT id,pharmacy_id,item_name,price,online_price,quantity,image,category,strength FROM store_items WHERE id=? AND branch_id=? AND is_active=1 AND is_online=1 AND quantity>0 AND (expiry_date IS NULL OR expiry_date=\'\' OR expiry_date=\'0000-00-00\' OR expiry_date>=CURDATE()) LIMIT 1'.($lock?' FOR UPDATE':'');$s=$db->prepare($sql);if(!$s)return null;$s->bind_param('ii',$pid,$bid);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}
function price(array $p):float{$base=(float)$p['price'];$online=(float)($p['online_price']??0);return round($online>0&&$online<$base?$online:$base,2);}
function orderNo(mysqli $db):string{for($i=0;$i<10;$i++){ $n='ORD-'.date('YmdHis').random_int(10,99);$s=$db->prepare('SELECT id FROM clients_orders WHERE order_number=? LIMIT 1');if(!$s)throw new RuntimeException('Unable to prepare order number.');$s->bind_param('s',$n);$s->execute();$exists=$s->get_result()->num_rows>0;$s->close();if(!$exists)return$n;}throw new RuntimeException('Unable to generate order number.');}

if($_SERVER['REQUEST_METHOD']!=='POST')out(false,'Invalid request method.');csrf();
$action=strtolower(trim((string)($_POST['action']??'')));
$bid=(int)($_POST['bid']??$_POST['branch_id']??$_SESSION['current_branch_id']??0);if($bid<=0)out(false,'No active branch selected.');
try{$br=branch($conn,$bid);$pid=(int)$br['pharmacy_id'];$_SESSION['current_branch_id']=$bid;$c=cart($bid);
if($action==='add'){
 $id=(int)($_POST['product_id']??$_POST['item_id']??0);$add=max(1,(int)($_POST['qty']??1));if($id<=0)out(false,'Invalid product.');$p=product($conn,$id,$bid);if(!$p)out(false,'This product is unavailable or out of stock.');$new=((int)($c[$id]['qty']??0))+$add;$stock=(int)$p['quantity'];if($new>$stock)out(false,"Only {$stock} unit(s) are available.",['available'=>$stock]);$c[$id]=['id'=>(int)$p['id'],'name'=>(string)$p['item_name'],'price'=>price($p),'qty'=>$new,'branch'=>$bid,'image'=>(string)($p['image']??''),'category'=>(string)($p['category']??''),'strength'=>(string)($p['strength']??''),'stock'=>$stock];$_SESSION['carts'][$bid]=$c;out(true,'Item added.',summary($c));
}
if($action==='get')out(true,'Cart loaded.',summary($c));
if($action==='update'){$id=(int)($_POST['item_id']??$_POST['product_id']??0);$q=(int)($_POST['qty']??0);if($id<=0||!isset($c[$id]))out(false,'Item is not in the cart.');if($q<=0){unset($c[$id]);$_SESSION['carts'][$bid]=$c;out(true,'Item removed.',summary($c));}$p=product($conn,$id,$bid);if(!$p){unset($c[$id]);$_SESSION['carts'][$bid]=$c;out(false,'This product is no longer available.');}$stock=(int)$p['quantity'];if($q>$stock)out(false,"Only {$stock} unit(s) are available.",['available'=>$stock]);$c[$id]['qty']=$q;$c[$id]['price']=price($p);$c[$id]['stock']=$stock;$_SESSION['carts'][$bid]=$c;out(true,'Cart updated.',summary($c));}
if($action==='remove'){$id=(int)($_POST['item_id']??$_POST['product_id']??0);unset($c[$id]);$_SESSION['carts'][$bid]=$c;out(true,'Item removed.',summary($c));}
if($action==='clear'){$_SESSION['carts'][$bid]=[];out(true,'Cart cleared.',summary([]));}
if($action==='checkout'){
 $clientId=(int)($_SESSION['client_id']??0);if($clientId<=0)out(false,'Please log in before placing an order.',['login_required'=>true]);
 $name=trim((string)($_POST['customer_name']??''));$phone=trim((string)($_POST['phone']??''));$address=trim((string)($_POST['address']??''));$payment=trim((string)($_POST['payment_method']??''));
 if($name===''||$phone===''||$address==='')out(false,'Please complete your name, phone number and delivery address.');if(!in_array($payment,['Cash on Delivery','Mobile Money','Bank'],true))out(false,'Please select a valid payment method.');if(!$c)out(false,'Your cart is empty.');
 $conn->begin_transaction();
 $s=$conn->prepare('SELECT id,full_name,phone,email FROM clients WHERE id=? LIMIT 1');if(!$s)throw new RuntimeException('Unable to verify account.');$s->bind_param('i',$clientId);$s->execute();$client=$s->get_result()->fetch_assoc();$s->close();if(!$client)throw new RuntimeException('Your online account could not be found. Please log in again.');
 $validated=[];$total=0.0;
 foreach($c as $ci){$id=(int)($ci['id']??0);$q=(int)($ci['qty']??0);if($id<=0||$q<=0)throw new RuntimeException('Invalid item in cart.');$p=product($conn,$id,$bid,true);if(!$p)throw new RuntimeException('One of the products is no longer available.');$stock=(int)$p['quantity'];if($q>$stock)throw new RuntimeException($p['item_name'].' has only '.$stock.' unit(s) available.');$unit=price($p);$line=round($unit*$q,2);$total+=$line;$validated[]=['id'=>$id,'qty'=>$q,'price'=>$unit];}
 $email=(string)($client['email']??'');
 $s=$conn->prepare('SELECT id FROM customers WHERE client_id=? AND pharmacy_id=? AND branch_id=? LIMIT 1 FOR UPDATE');if(!$s)throw new RuntimeException('Unable to prepare customer profile.');$s->bind_param('iii',$clientId,$pid,$bid);$s->execute();$customer=$s->get_result()->fetch_assoc();$s->close();
 if($customer){$cid=(int)$customer['id'];$s=$conn->prepare('UPDATE customers SET name=?,phone=?,email=?,address=? WHERE id=? LIMIT 1');if(!$s)throw new RuntimeException('Unable to update customer profile.');$s->bind_param('ssssi',$name,$phone,$email,$address,$cid);if(!$s->execute())throw new RuntimeException('Unable to save delivery details.');$s->close();}
 else{$s=$conn->prepare('SELECT id,client_id FROM customers WHERE branch_id=? AND phone=? LIMIT 1 FOR UPDATE');if(!$s)throw new RuntimeException('Unable to verify phone number.');$s->bind_param('is',$bid,$phone);$s->execute();$owner=$s->get_result()->fetch_assoc();$s->close();if($owner&&((int)($owner['client_id']??0)!==$clientId))throw new RuntimeException('That phone number is already registered to another customer at this branch.');if($owner){$cid=(int)$owner['id'];$s=$conn->prepare('UPDATE customers SET client_id=?,pharmacy_id=?,name=?,email=?,address=? WHERE id=? LIMIT 1');if(!$s)throw new RuntimeException('Unable to update customer.');$s->bind_param('iisssi',$clientId,$pid,$name,$email,$address,$cid);if(!$s->execute())throw new RuntimeException('Unable to save customer details.');$s->close();}else{$s=$conn->prepare('INSERT INTO customers (pharmacy_id,branch_id,client_id,name,phone,email,address) VALUES (?,?,?,?,?,?,?)');if(!$s)throw new RuntimeException('Unable to create customer profile.');$s->bind_param('iiissss',$pid,$bid,$clientId,$name,$phone,$email,$address);if(!$s->execute())throw new RuntimeException('Unable to save customer profile.');$s->close();}}
 $number=orderNo($conn);$total=round($total,2);$s=$conn->prepare("INSERT INTO clients_orders (client_id,order_number,total_amount,payment_method,status,pharmacy_id,branch_id) VALUES (?,?,?,?,'Pending',?,?)");if(!$s)throw new RuntimeException('Unable to create online order.');$s->bind_param('isdsii',$clientId,$number,$total,$payment,$pid,$bid);if(!$s->execute())throw new RuntimeException('Unable to save online order.');$oid=(int)$conn->insert_id;$s->close();if($oid<=0)throw new RuntimeException('Online order was not created.');
 $is=$conn->prepare('INSERT INTO clients_order_items (order_id,product_id,quantity,price_at_purchase,pharmacy_id,branch_id) VALUES (?,?,?,?,?,?)');if(!$is)throw new RuntimeException('Unable to prepare order items.');$us=$conn->prepare('UPDATE store_items SET quantity=quantity-? WHERE id=? AND pharmacy_id=? AND branch_id=? AND quantity>=? LIMIT 1');if(!$us)throw new RuntimeException('Unable to prepare stock update.');foreach($validated as $v){$id=$v['id'];$q=$v['qty'];$pr=$v['price'];$is->bind_param('iiidii',$oid,$id,$q,$pr,$pid,$bid);if(!$is->execute())throw new RuntimeException('Unable to save order item.');$us->bind_param('iiiii',$q,$id,$pid,$bid,$q);if(!$us->execute()||$us->affected_rows!==1)throw new RuntimeException('Stock changed while processing your order. Please try again.');}$is->close();$us->close();$conn->commit();$_SESSION['carts'][$bid]=[];out(true,'Your order has been placed successfully.',['order_id'=>$oid,'order_number'=>$number,'total'=>$total,'payment_method'=>$payment,'branch_id'=>$bid,'pharmacy_id'=>$pid]);
}
out(false,'Unknown cart action.');
}catch(Throwable $e){try{$conn->rollback();}catch(Throwable $ignore){}error_log('ONLINE CART API: '.$e->getMessage());out(false,$e->getMessage());}
